apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mico
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
images:
  - name: mico-server
    newTag: latest
